//! **EVERY ASSERTION IN THE SOURCE, WHETHER OR NOT ITS CODE IS COMPILED.**
//! Zig analyzes only what is referenced, so an assertion in a function nothing
//! calls never instantiates its `Site`, and a `sometimes` that cannot run is
//! the one the catalog most needs to report. Referencing declarations reaches
//! plain functions but not generic ones or ones taking `anytype`, whose bodies
//! cannot be analyzed without arguments. So, as Antithesis's Go SDK does with
//! its instrumentor, this reads the source instead.
//!
//!   scan <out.zig> <root-dir> <file, relative to root-dir>...
//!
//! It parses each file with `std.zig.Ast` and finds every call named
//! `always`, `alwaysOrUnreachable`, `sometimes`, `reachable`,
//! `@"unreachable"` or one of the numeric comparisons (`alwaysGreaterThan`
//! and the rest) whose first argument is `@src()` and whose message is a
//! string literal. It writes one Zig file:
//!
//!   pub fn sites(comptime module: [:0]const u8, comptime file: []const u8) void
//!
//! which `coverage.catalogFile` calls at comptime from each scanned file, with
//! that file's own `@src()`. Each call to `coverage.register` it makes names
//! exactly the `Site` the real call names (`@src()`'s line and column are the
//! token's, plus one), so a site is one Site whether or not its code is
//! compiled, and nothing is merged at run time.
//!
//! A call inside a `test` block is skipped: a program never compiles those.
//! A message that is not a string literal is skipped with a warning, and that
//! site is cataloged only if its code is compiled.
const std = @import("std");
const Ast = std.zig.Ast;

const kinds = [_]struct { name: []const u8, tag: []const u8, msg_arg: usize }{
    .{ .name = "always", .tag = "always", .msg_arg = 2 },
    .{ .name = "alwaysOrUnreachable", .tag = "always_or_unreachable", .msg_arg = 2 },
    .{ .name = "sometimes", .tag = "sometimes", .msg_arg = 2 },
    .{ .name = "reachable", .tag = "reachable", .msg_arg = 1 },
    .{ .name = "@\"unreachable\"", .tag = "@\"unreachable\"", .msg_arg = 1 },
    // The numeric comparisons: `(@src(), left, right, message, details)`.
    .{ .name = "alwaysGreaterThan", .tag = "always_greater_than", .msg_arg = 3 },
    .{ .name = "alwaysGreaterThanOrEqualTo", .tag = "always_greater_than_or_equal_to", .msg_arg = 3 },
    .{ .name = "alwaysLessThan", .tag = "always_less_than", .msg_arg = 3 },
    .{ .name = "alwaysLessThanOrEqualTo", .tag = "always_less_than_or_equal_to", .msg_arg = 3 },
    .{ .name = "sometimesGreaterThan", .tag = "sometimes_greater_than", .msg_arg = 3 },
    .{ .name = "sometimesGreaterThanOrEqualTo", .tag = "sometimes_greater_than_or_equal_to", .msg_arg = 3 },
    .{ .name = "sometimesLessThan", .tag = "sometimes_less_than", .msg_arg = 3 },
    .{ .name = "sometimesLessThanOrEqualTo", .tag = "sometimes_less_than_or_equal_to", .msg_arg = 3 },
};

pub fn main(init: std.process.Init) !void {
    const arena = init.arena.allocator();
    const io = init.io;
    const args = try init.minimal.args.toSlice(arena);
    if (args.len < 3) {
        std.log.err("usage: scan <out.zig> <root-dir> <file>...", .{});
        return error.Usage;
    }
    const out_path, const root = .{ args[1], args[2] };

    var out: std.ArrayList(u8) = .empty;
    try out.appendSlice(arena,
        \\//! GENERATED by zig-coverage-sdk's tools/scan.zig: every assertion in the
        \\//! scanned files, for `coverage.catalogFile`. Do not edit.
        \\const std = @import("std");
        \\const coverage = @import("coverage");
        \\
        \\pub fn sites(comptime module: [:0]const u8, comptime file: []const u8) void {
        \\
    );

    var root_dir = try std.Io.Dir.cwd().openDir(io, root, .{});
    defer root_dir.close(io);
    for (args[3..]) |rel| {
        const src = try root_dir.readFileAllocOptions(io, rel, arena, .unlimited, .of(u8), 0);
        var tree = try Ast.parse(arena, src, .zig);
        if (tree.errors.len != 0) {
            std.log.err("{s}: does not parse", .{rel});
            return error.ParseError;
        }
        try out.print(arena, "    if (comptime std.mem.eql(u8, file, \"{s}\")) {{\n", .{rel});
        try scanFile(arena, &out, &tree, rel);
        try out.appendSlice(arena, "    }\n");
    }
    try out.appendSlice(arena, "}\n");
    try std.Io.Dir.cwd().writeFile(io, .{ .sub_path = out_path, .data = out.items });
}

const Span = struct { first: Ast.TokenIndex, last: Ast.TokenIndex, name: []const u8, is_test: bool };

fn scanFile(gpa: std.mem.Allocator, out: *std.ArrayList(u8), tree: *Ast, file: []const u8) !void {
    // Every fn and test body, so a call can find its innermost enclosure,
    // which is what `@src().fn_name` names.
    var spans: std.ArrayList(Span) = .empty;
    for (0..tree.nodes.len) |i| {
        const node: Ast.Node.Index = @enumFromInt(i);
        switch (tree.nodeTag(node)) {
            .fn_decl => {
                var buf: [1]Ast.Node.Index = undefined;
                const proto = tree.fullFnProto(&buf, node).?;
                const name = if (proto.name_token) |t| tree.tokenSlice(t) else "";
                try spans.append(gpa, .{ .first = tree.firstToken(node), .last = tree.lastToken(node), .name = name, .is_test = false });
            },
            .test_decl => try spans.append(gpa, .{ .first = tree.firstToken(node), .last = tree.lastToken(node), .name = "", .is_test = true }),
            else => {},
        }
    }

    for (0..tree.nodes.len) |i| {
        const node: Ast.Node.Index = @enumFromInt(i);
        var buf: [1]Ast.Node.Index = undefined;
        const call = tree.fullCall(&buf, node) orelse continue;
        const name = tree.tokenSlice(tree.lastToken(call.ast.fn_expr));
        const k = for (kinds) |k| {
            if (std.mem.eql(u8, k.name, name)) break k;
        } else continue;
        if (call.ast.params.len <= k.msg_arg) continue;
        const src_arg = call.ast.params[0];
        switch (tree.nodeTag(src_arg)) {
            .builtin_call_two, .builtin_call_two_comma => {},
            else => continue,
        }
        if (!std.mem.eql(u8, tree.tokenSlice(tree.nodeMainToken(src_arg)), "@src")) continue;

        const loc = tree.tokenLocation(0, tree.nodeMainToken(src_arg));
        const msg = call.ast.params[k.msg_arg];
        if (tree.nodeTag(msg) != .string_literal) {
            std.log.warn("{s}:{d}:{d}: the message is not a string literal, so this site is not cataloged", .{ file, loc.line + 1, loc.column + 1 });
            continue;
        }
        var best: ?Span = null;
        for (spans.items) |s| {
            if (s.first <= tree.nodeMainToken(node) and tree.nodeMainToken(node) <= s.last and
                (best == null or s.first >= best.?.first)) best = s;
        }
        const enclosing = best orelse continue; // at container level: not a call site
        if (enclosing.is_test) continue;
        try out.print(gpa, "        coverage.register(.{{ .module = module, .file = \"{s}\", .fn_name = \"{s}\", .line = {d}, .column = {d} }}, .{s}, {s});\n", .{
            file, enclosing.name, loc.line + 1, loc.column + 1, k.tag, tree.tokenSlice(tree.nodeMainToken(msg)),
        });
    }
}
